branches:
  only:
    - develop
    - master

service:
  -docker

before_scripts:
  docker pull $DOCKER_USERNAME/nodexperiencetest

script:
  docker run $DOCKER_USERNAME/nodexperiencetest

after_success:
   - sudo docker build -t $DOCKER_USERNAME/nodexperience --build-arg ATLAS_PASSWORD=$ATLAS_PASSWORD --build-arg MAIL_PASSWORD=$MAIL_PASSWORD --build-arg PHOTO_SERVICE=$PHOTO_SERVICE  .
   - echo $DOCKER_PASSWORD  
   - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
   - docker push $DOCKER_USERNAME/nodexperience:latest