branches:
  only:
    - develop
    - master

service:
  -docker

matrix: 
  before_scripts:
    docker pull sergio19006/nodexperiencetest

  script:
    docker run sergio19006/nodexperiencetest

    after_success:
      - docker build -t $DOCKER_USERNAME/nodexperiencetest .   
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/nodexperiencetest:latest
