language: node_js
node_js:
  - node
branches:
  only:
    - develop

service:
  -docker

before_scripts:
  docker pull sergio19006/nodexperiencetest

script:
  docker run sergio19006/nodexperiencetest
cache:
  directories:
    - node_modules
