apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodexperience
spec:
  replicas: 1
  selector:
    matchLabels:
      role: node
  template:
    metadata:
      labels:
        role: node
    spec:
      containers:
      - name: nodexperience
        image: nodexperience
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
